# 配置工作流
name: 工作流
# 在 push 时执行
on:
  push:
    branches:
      - master

# 配置工作
jobs:
  # automation-deploy 工作
  automation-deploy:
    # 自动化部署
    name: 自动化部署
    # 运行于 ubuntu 系统
    runs-on: ubuntu-latest
    # 配置工作步骤
    steps:
    - name: 检出代码
      uses: actions/checkout@master

    - name: 安装node
      uses: actions/setup-node@master
      with:
        node-version: 12

    - name: 安装gitbook
      run: |
        npm install gitbook-cli
        node_modules/.bin/gitbook -v
        node_modules/.bin/gitbook install

    - name: 构建与发布
      run: |
        git config user.name "zhangxishuo"
        git config user.email "zhangxishuo1998@outlook.com"
        node_modules/.bin/gitbook build
        git push https://${{ secrets.ACCESS_TOKEN }}@github.com/zhangxishuo/notes.git `git subtree split --prefix=_book`:gh-pages --force
